# Generated by Django 3.1.7 on 2021-04-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('class_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('class_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.class')),
            ],
        ),
    ]
