# Generated by Django 3.1.7 on 2021-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210411_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
                ('birthday', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
