# Generated by Django 3.1.7 on 2021-04-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210411_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('hours', models.IntegerField()),
                ('class_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.class')),
                ('teacher_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.teacher')),
            ],
        ),
    ]
