# Generated by Django 3.1.7 on 2021-09-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'default_permissions': ()},
        ),
    ]
