# Generated by Django 3.1.7 on 2021-04-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('commentary', models.TextField()),
                ('class_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.class')),
                ('discipline_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.discipline')),
                ('teacher_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.teacher')),
            ],
        ),
    ]
