# Generated by Django 3.1.7 on 2021-09-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210917_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={},
        ),
    ]
