# Generated by Django 3.1.7 on 2021-04-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField()),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.student')),
                ('task_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='school.task')),
            ],
        ),
    ]
