# Generated by Django 3.1.7 on 2021-09-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210917_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
