# Generated by Django 3.1.7 on 2021-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_delete_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='grade',
        ),
    ]
