# Generated by Django 3.1.7 on 2021-04-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofclass',
            options={'verbose_name': 'Type of class', 'verbose_name_plural': 'Types of classes'},
        ),
    ]
