# Generated by Django 3.1.7 on 2021-09-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210929_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='class_id',
            new_name='grade',
        ),
    ]
