# Generated by Django 3.1.7 on 2021-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20210412_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='final_score',
            field=models.IntegerField(default='poppi'),
        ),
    ]
