# Generated by Django 3.1.7 on 2021-08-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210721_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='final_score',
            field=models.IntegerField(),
        ),
    ]
