# Generated by Django 3.1.7 on 2021-09-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210929_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
