# Generated by Django 3.1.7 on 2021-08-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210803_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('end_date',)},
        ),
    ]
