# Generated by Django 3.1.7 on 2021-09-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20210929_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
