# Generated by Django 3.1.7 on 2021-09-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210929_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discipline_id',
            new_name='discipline',
        ),
    ]
