# Generated by Django 3.1.7 on 2021-09-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210929_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='student_id',
            new_name='student',
        ),
    ]
