# Generated by Django 3.1.7 on 2021-08-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210822_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('end_date',)},
        ),
    ]
