# Generated by Django 3.1.7 on 2021-08-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20210822_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='type_of_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.typeofclass'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='discipline_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.discipline'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='task_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.task'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='task',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AlterField(
            model_name='task',
            name='discipline_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.discipline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
    ]
