# Generated by Django 3.1.7 on 2021-08-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210826_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class', verbose_name='Choose a class:'),
        ),
    ]
